### ISSUE TITLE
css crash in checkout

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/edje-wc-library#1]
pak mau tanya ini knp ya pak http://prntscr.com/g90r2w ko setalh saya aktifkan cart dan checkout rusak ya pak tidak seperti di gambar demo,

**Comment by frezendisney** [comment]
bisa di compress enggak om. jadi khusus ke checkout aja css'y. ini saya konflik dengan css themes yg saya pakai. mungkin ada solusi om untuk custom bagian checkoutnya. problem jg dipage cart jg. masalah sama konflik dengn css utama di themes wp

**Comment by frezendisney** [comment]
bbrp udh solving pak. konflik dengan template themes saya. dan akhirnya harus saya remove file2 yg bawaan template buat. masih ada bbrp problem lagi mengenai cart dll

**Comment by hrsetyono** [comment]
@frezendisney 

> pak mau tanya ini knp ya pak http://prntscr.com/g90r2w ko setalh saya aktifkan cart dan checkout rusak ya pak tidak seperti di gambar demo,

CSS nya sudah aku buat supaya semua yang `enqueue` di bawah 1000 akan ke override semua. CSS bapak tolong diganti priority nya di bawah 1000.

Baru saya update supaya semua CSS lain yang di bawah priority 999,999 kehapus. Jadi skrg ga bakal crash lagi kecuali bapak enqueu script sendiri di atas 1,000,000

> bisa di compress enggak om. jadi khusus ke checkout aja css'y. ini saya konflik dengan css themes yg saya pakai. mungkin ada solusi om untuk custom bagian checkoutnya. problem jg dipage cart jg. masalah sama konflik dengn css utama di themes wp

Seharusnya CSS itu khusus di load pas checkout sama thank you page aja. Coba aku cek lagi

**Comment by hrsetyono** [comment]
> Seharusnya CSS itu khusus di load pas checkout sama thank you page aja. Coba aku cek lagi

Iya benar, CSS dan JS custom saya cuma ke load pas Checkout dan Thank You saja. jadi tidak mungkin crash di luar itu
