### ISSUE TITLE
Designed to work with Timber?

### ISSUE THREAD

**Issue by firstchair** [hrsetyono/edje-wc-library#14]
Hi Pixel Studio,

Nice addition to wooCommerce! I'm trying to implements this, but you say in the description that its designed to work with Timber too? I see "Simplify WooCommerce complicated features. Designed to work with Timber." Can't see how its easily integrated with all the php-templates. Hope to hear! :-)

Keep up the great work!

Lukas

**Comment by hrsetyono** [comment]
Hi @firstchair 

Thank you for giving our plugin a try. The "designed to work with TImber" is no longer true.

At first I want to make WooCommerce theme to be fully editable with Timber. But it's way too much work. It's easier to just use the native function / action and adapt the styling around their HTML markup.

You can check my theme that's made entirely made with Timber here https://github.com/hrsetyono/edje-wp-theme. **Note**: I accidentally pushed a beta code to master branch, for the working theme, check out the [latest release](https://github.com/hrsetyono/edje-wp-theme/releases)

This theme also has WooCommerce integration in `/views/shop` but as you can see, it's just a collection of native functions and actions

**Comment by firstchair** [comment]
Thanks for your reply. Im working atm on a integration for Woocommerce w/ Timber.
I'll have a look if i can use some elements :-)
