### ISSUE TITLE
fiel kota tidak dihidden

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/edje-wc-library#3]
pak ada bugs lagi ini harusny di hidden pak http://prntscr.com/gadq9k untuk data billingnnya

**Comment by frezendisney** [comment]
dan untuk class size-post-thumbnail ini jadi duplicate pak di email newslateer bpk bisa check aja stelah order akan ada gambar besar muncul. itu normalnya kecil. dan saya setting class untuk size-post-thumbnail saya display none

**Comment by hrsetyono** [comment]
Untuk bug yg tidak di hidden itu bagian dari woocommerce-indo-shipping nya. Queue priority dari plugin shipping blm saya naikkan.

Update nya sudah saya luncurkan https://github.com/hrsetyono/woocommerce-indo-shipping/releases/tag/1.1.2

Sekalian sudah saya perbaiki weight calculator nya.

> dan untuk class size-post-thumbnail ini jadi duplicate pak di email newslateer bpk bisa check aja stelah order akan ada gambar besar muncul. itu normalnya kecil. dan saya setting class untuk size-post-thumbnail saya display none

Hmm aneh, saya tidak pernah otak atik bagian newsletter. Masa CSS dari checkout ikut masuk di email?

Bisa tolong screenshot nya?

**Comment by frezendisney** [comment]
ini plugin lagi active http://prntscr.com/gae0df 
dan ini saat di non actifkan http://prntscr.com/gae130
itu saya cb di localhost

dan masalah ini jg buat duplicate gambar dicheckout pak. jadi saya akalin di bagian cart saya disable thumbnailnya yg size jumbo. 

kira2 knp y pak? aneh jg ya.

**Comment by hrsetyono** [comment]
Ah sepertinya karena saya ada buat Hook untuk menambahkan gambar di Checkout page. Kan harusnya tidak ada thumbnail pas Checkout.

Coba saya cari cara supaya tidak ke apply ke semua tempat.

**Comment by frezendisney** [comment]
iya pak. dimana2 duplicate itu. hehehehe siap pak.

**Comment by frezendisney** [comment]
setlah di upadate versi agak mendingan nih pak ngeload di checkout udh enggak berat kaya sblumnya rada aneh. ditunggu y pak yg duplicate. kayanya masih ada lagi deh. nanti saya infoin beserta screenshotnya. overal keren banget pluginnya hehehe

**Comment by hrsetyono** [comment]
> setlah di upadate versi agak mendingan nih pak ngeload di checkout udh enggak berat kaya sblumnya rada aneh. ditunggu y pak yg duplicate. kayanya masih ada lagi deh. nanti saya infoin beserta screenshotnya. overal keren banget pluginnya hehehe

Trims pak, plugin ini saya buat karena banyak visitor yang abandon checkout nya. Salah satu elemen paling penting dari plugin ini adalah memindah EMAIL field ke atas. Jadi kalau tengah2 abandoned, sudah dapat email nya untuk dikejar. (perlu Pakai Abandoned Checkout plugin, ada banyak)

**Comment by frezendisney** [comment]
oh iya ya baru kepikiran saya pak. bnr juga pak. hehehe. thanks banget pak ilmunya.  oh iya yg rekomended buat Abandoned Checkout plugin kira2 yg mana ya pak ? mungkin bpk punya info buat saya.

**Comment by hrsetyono** [comment]
Saya test email nya, kok tidak ada thumbnail? Apa bapak pakai **plugin tambahan** untuk mengganti format email nya?

Untuk thumbnail nya sudah saya update supaya tidak muncul selain di halaman checkout. Tapi entah apakah email itu dianggap halaman checkout. Mohon di tes.

Release: https://github.com/hrsetyono/woocommerce-edje/releases/tag/1.1.4a

**Comment by frezendisney** [comment]
ok pak siap saya cb check lgi dan memperbarui pluginnya
