### ISSUE TITLE
Web ui edge

### ISSUE THREAD

**Issue by frezendisney** [hrsetyono/edje-wc-library#4]
pak mau tanya klw mau nambh gambar ini ada web ui'y enggak sih di dasboard admin. dan lokasinya dimana ya pak? saya cari2 enggak nemu

**Comment by hrsetyono** [comment]
Gambar banner di atas itu di Pages > Checkout > upload featured image

Ini guide nya https://github.com/hrsetyono/woocommerce-edje/wiki/Checkout-Page#2-add--change-top-banner
