### ISSUE TITLE
css pada halaman checkout tidak sempurna

### ISSUE THREAD

**Issue by alfarioekaputra** [hrsetyono/edje-wc-library#5]
selamat siang,

saya mau tanya, saya menggunakan wordpress versi 4.8.2 dan woocomerce versi 3.2.1
untuk woocommerce-edje versi 1.1.4a

dan menggunakan theme storefont, pada halaman checkout css tidak terload sempurna, seperti pada gambar dibawah

![screen shot 2017-10-27 at 11 13 21 am](https://user-images.githubusercontent.com/650641/32087766-60670a72-bb08-11e7-9bd4-68682d86a82d.png)

**Comment by hrsetyono** [comment]
Hmm aneh, seharus nya navigation tidak muncul karena `get_header` tidak saya panggil.

Bisa tolong coba plugin lain dimatikan satu per satu? Kemungkinan ada yang clash.

Trims

**Comment by konservasi** [comment]
sama,saya juga mengalami hal yang sama. Kalau gak pakai banner itu gimana cara editnya?

**Comment by hrsetyono** [comment]
@konservasi maaf tidak bisa tanpa banner. Bapak pakai theme apa ya?

**Comment by konservasi** [comment]
apa pengaruh ke header theme klo pake banner? sy pake theme e-store

**Comment by hrsetyono** [comment]
kemungkinan tidak compatible dengan theme nya. coba pakai storefront

**Comment by konservasi** [comment]
bannernya tidak saya pasang sih mas. anyway thanks sarannya. mungkin lain
kali akan saya edit pluginnya atau mau di bikinkan versi yang tidak pakai
banner?

2017-12-15 16:56 GMT+07:00 Henner R Setyono <notifications@github.com>:

**Comment by hrsetyono** [comment]
@konservasi Silahkan di edit pluginnya. Nanti kalau sudah jadi boleh share ke saya? coba saya lihat2 hehe
